{
  imports = [
    ./amnezia-vpn.nix
    ./appimage.nix
    ./audio.nix
    ./boot.nix
    ./bluetooth.nix
    ./gnupg.nix
    ./network.nix
    ./nh.nix
    ./niri.nix
    ./nix.nix
    ./powermgmt.nix
    ./security.nix
    ./tailscale.nix
    ./timezone.nix
    ./udisks.nix
    ./users.nix
    ./virtualisation.nix
  ];
}
