{
  imports = [
    ./amnezia-vpn.nix
    ./appimage.nix
    ./audio.nix
    ./boot.nix
    ./gamemode.nix
    ./gnome.nix
    ./network.nix
    ./nh.nix
    ./nix.nix
    ./powermgmt.nix
    ./security.nix
    ./ssh-agent.nix
    ./tailscale.nix
    ./timezone.nix
    ./users.nix
    ./virtualisation.nix
  ];
}
